function [Fitresult, gof] = createFit1(turns, counts_sec)
%CREATEFIT1(TURNS,COUNTS_SEC)
%  Create a fit.
%
%  Data for 'discriminatorCurve' fit:
%      X Input : turns
%      Y Output: counts_sec
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Nov-2018 19:11:05


%% Fit: 'discriminatorCurve'.
[XData, YData] = prepareCurveData( turns, counts_sec );

% Set up fittype and options.
Ft = fittype( 'a * exp(-(b*x+c)^2)', 'independent', 'x', 'dependent', 'y' );
Opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
Opts.Display = 'Off';
Opts.StartPoint = [0.31304602161505 0.233109816104957 0.867435074825857];

% Fit model to data.
[Fitresult, gof] = fit( XData, YData, Ft, Opts );

% Plot fit with data.
figure( 'Name', 'discriminatorCurve' );
g = plot( Fitresult, XData, YData );
legend( g, 'counts_sec vs. turns', 'discriminatorCurve', 'Location', 'NorthEast' );
% Label axes
xlabel turns
ylabel counts_sec
grid on


