function [FITRESULT, GOF] = createFit1(X, Y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'angular_l' fit:
%      X Input : X
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Nov-2018 15:24:07


%% Fit: 'angular_l'.
[XXData, YYData] = prepareCurveData( X, Y );

% Set up fittype and options.
FT = fittype( 'a / x^4', 'independent', 'x', 'dependent', 'y' );
OPTS = fitoptions( 'Method', 'NonlinearLeastSquares' );
OPTS.Display = 'Off';
OPTS.StartPoint = 0.132420604790519;

% Fit model to data.
[FITRESULT, GOF] = fit( XXData, YYData, FT, OPTS );

% Plot fit with data.
figure( 'Name', 'angular_l' );
h = plot( FITRESULT, XXData, YYData );
legend( h, 'Y vs. X', 'angular_l', 'Location', 'NorthEast' );
% Label axes
xlabel X
ylabel Y
grid on


