function [fitresult, gof] = createFit(turns, counts_sec)
%CREATEFIT(TURNS,COUNTS_SEC)
%  Create a fit.
%
%  Data for 'erf' fit:
%      X Input : turns
%      Y Output: counts_sec
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Nov-2018 15:56:37


%% Fit: 'erf'.
[xData, yData] = prepareCurveData( turns, counts_sec );

% Set up fittype and options.
ft = fittype( 'a*erf(b*x + c)+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [-20 1.2 -3.5 20]; % startpoints for [a, b, c, d]
    % variable = value (?, ?)
    % a =      -18.01  (-19.26, -16.77)
    % b =       1.359  (1.001, 1.716)
    % c =      -4.978  (-6.301, -3.656)
    % d =       17.84  (16.69, 18.99)

    % goodness of fit (gof):
            %SSE: 31.8
            %R-square: 0.992
            %adjusted R-square: 0.99
            %RMSE: 1.628
            
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'erf' );
h = plot( fitresult, xData, yData );
legend( h, 'counts_sec vs. turns', 'erf', 'Location', 'NorthEast' );
% Label axes
xlabel turns
ylabel counts_sec
grid on


