function [fitresult, gof] = createFit1(XX, YY)
%CREATEFIT1(XX,YY)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : XX
%      Y Output: YY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Nov-2018 22:20:18

% xData = XX  = log(X) = ln(sin(theta/2))
% yData = YY = log(Y) = ln(Na/ (OmegaD * t))
%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( XX, YY );

% Set up fittype and options.
ft = fittype( 'a*x + b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0579159481171146 0.304881922129305];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'YY vs. XX', 'untitled fit 2', 'Location', 'NorthEast' );
% Label axes
xlabel XX
ylabel YY
grid on


